### ISSUE TITLE
Username and Password Not Found

### ISSUE THREAD

**Issue by manimike00** [SoftwareWorkersSrl/SaltWebGui#1]
I'm not able to login in SaltWebGui using this documentation https://media.readthedocs.org/pdf/saltwebgui/latest/saltwebgui.pdf. They don't provide me any username or password to login.
Is there any default username and password is present?

**Comment by Sjd-Risca** [comment]
At current state the authentication is run by saltstack itself, therefore it depends by which user and which backend you have enabled. At current state the possible auth system are: [auth modules](https://docs.saltstack.com/en/latest/ref/auth/all/index.html)

At page 6 of the documentation there is an example using pam:

> And set-up proper user permission (here enable system usermylinuxuser):
```
external_auth:
  pam:
    mylinuxuser:
      - ".*"
      - "@runner"
      - "@wheel"
```

> Themylinuxuserhas to be a system user (it is possible to create a custom one withadduser mylinuxyser).
